version: '3.7'

services:
  zeebe:
    image: camunda/zeebe:8.2.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
    networks:
      - zeebe_network

  operate:
    image: camunda/operate:8.2.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - CAMUNDA_OPERATE_ZEEBE_GATEWAY_ADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "8080:8080"
    depends_on:
      - zeebe
      - elasticsearch
    networks:
      - zeebe_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - zeebe_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - zeebe_network

networks:
  zeebe_network:
    driver: bridge
